In [1]:
import pandas as pd
import datetime

In [2]:
dcc_assets = pd.read_csv('https://cfde-drc.s3.amazonaws.com/database/files/current_dcc_assets.tsv', sep="\t")
dcc_assets.sort_values('lastmodified').tail()

,link,lastmodified,current,creator,dcc_id,drcapproved,dccapproved,deleted,created
445,https://cfde-drc.s3.amazonaws.com/geo_project/...,2026-09-16 15:37:42.091,True,NaN,6af15c97-f26d-577e-8be8-1c90c3127543,True,True,False,2026-09-16 15:37:42.091
469,https://cfde-drc.s3.amazonaws.com/KidsFirst/C2...,2026-09-16 19:33:44.525,True,NaN,65af85ae-82d5-5b81-bc66-6bddaa6420ce,True,True,False,2026-09-16 19:33:44.525
499,https://cfde-drc.s3.amazonaws.com/SPARC/C2M2/2...,2026-09-17 01:49:40.406,True,NaN,2399794e-74c6-5735-a039-0782cdeeb1e2,True,True,False,2026-09-17 01:49:40.406
527,https://cfde-drc.s3.amazonaws.com/GlyGen/C2M2/...,2026-09-18 15:21:45.166,True,NaN,e31052b0-ac50-5ede-9828-698ff3610427,True,True,False,2026-09-18 15:21:45.166
310,https://cfde-drc.s3.amazonaws.com/GlyGen/XMT/2...,2026-09-18 15:46:19.363,True,NaN,e31052b0-ac50-5ede-9828-698ff3610427,True,True,False,2026-09-18 15:46:19.363

In [4]:
current_dcc_assets = dcc_assets[dcc_assets.created.apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S.%f")) > datetime.datetime(2026, 6, 15, 23, 59, 59)]

In [5]:
dcc = pd.read_csv("https://cfde-drc.s3.amazonaws.com/database/files/current_dccs.tsv", sep="\t", index_col=0)

In [6]:
current_dcc_assets["DCC"] = [dcc.loc[i, 'short_label'] for i in current_dcc_assets.dcc_id]

/var/folders/wq/7bkxhy8j7ql194c1fbby4gy40000gn/T/ipykernel_78344/1305888965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_dcc_assets["DCC"] = [dcc.loc[i, 'short_label'] for i in current_dcc_assets.dcc_id]

In [7]:
file_assets = pd.read_csv("https://cfde-drc.s3.amazonaws.com/database/files/current_file_assets.tsv", sep="\t")
file_assets = file_assets.set_index("link")
file_assets.head()

,filetype,filename,size,sha256checksum
link,,,,
https://cfde-drc.s3.amazonaws.com/ExRNA/C2M2/2026-08-28/CFDE08272026_C2M2.zip,C2M2,CFDE08272026_C2M2.zip,16863896,+L/uShwIaDzGX1O8bY3NaMiU0+5Um+/OqM34QXYixlg=
https://cfde-drc.s3.amazonaws.com/Metabolomics/C2M2/2026-09-14/MW_submission_packet_20260914.zip,C2M2,MW_submission_packet_20260914.zip,24499914,rR4YztvTnGNccUdK/GCdEnHjIpVvKwkxcg1SzkLdtpk=
https://cfde-drc.s3.amazonaws.com/geo_project/C2M2/2026-09-16/GEO_metadata_20260914.zip,C2M2,GEO_metadata_20260914.zip,8472653,MvfRoBtUwS6Po3J3k3Nie7c7cO+Kq6TzFhUN+o5LF9E=
https://cfde-drc.s3.amazonaws.com/KidsFirst/C2M2/2026-09-16/2026Q4_C2M2_datapackage.zip,C2M2,2026Q4_C2M2_datapackage.zip,143013499,6DV5V4q+GIT0ZN8WPjwz7wQ/uxDkc0X4ReG7sQwnFLc=
https://cfde-drc.s3.amazonaws.com/SPARC/C2M2/2026-09-17/C2M2_datapackage_20260916.zip,C2M2,C2M2_datapackage_20260916.zip,28956042,2FPJ46AT/l0SDpqlB+1el0CpVnejtosNGLBNoySU0d0=

In [8]:
code_assets = pd.read_csv("https://cfde-drc.s3.amazonaws.com/database/files/current_code_assets.tsv", sep="\t")
code_assets = code_assets.set_index("link")
code_assets.head()

,type,name,description,openAPISpec,smartAPISpec,smartAPIURL,entityPageExample
link,,,,,,,
https://brl-bcm.stoplight.io/docs/exrna-atlas-json-api/ZG9jOjQ1Mg-overview,API,exRNA Atlas JSON-LD,NaN,True,False,NaN,NaN
https://github.com/nih-cfde/LINCS-metadata/blob/main/scripts/build_file_lincs2021.py,ETL,build_file_lincs2021.py,NaN,NaN,NaN,NaN,NaN
https://smart-api.info/ui/fdb3ecfcf5006a142d3f5522930324f1,API,SigCom LINCS Data,NaN,True,True,NaN,NaN
https://smart-api.info/ui/75cfc060ea7bec431a356c00c4a67c74,API,SigCom LINCS Metadata,NaN,True,True,NaN,NaN
https://smart-api.info/ui/d2cd419fdeace3e941984bc542e9383f,API,Enrichr,NaN,True,True,NaN,NaN

In [9]:
current_dcc_assets['Asset Type'] = ''
for k,v in current_dcc_assets.iterrows():
	link = v["link"]
	asset = file_assets.loc[link, 'filetype'] if link in file_assets.index else code_assets.loc[link, 'type']
	# asset = file_assets.loc[link, 'filetype'] #if link in file_assets.index else 'ETL'
	current_dcc_assets.loc[k, 'Asset Type'] = asset

/var/folders/wq/7bkxhy8j7ql194c1fbby4gy40000gn/T/ipykernel_78344/4159639814.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_dcc_assets['Asset Type'] = ''

In [10]:
current_dcc_assets[['DCC', 'Asset Type', 'dccapproved', 'drcapproved', 'created', 'deleted', 'current']].sort_values('created', ascending=False).to_csv("092026submissions.tsv", sep="\t", index=False)