In [1]:
import pandas as pd
import datetime

In [2]:
dcc_assets = pd.read_csv('https://cfde-drc.s3.amazonaws.com/database/files/current_dcc_assets.tsv', sep="\t")
dcc_assets.sort_values('lastmodified').tail()

,link,lastmodified,current,creator,dcc_id,drcapproved,dccapproved,deleted,created
480,https://github.com/MaayanLab/Playbook-Workflow...,2026-04-13 14:50:20.343,True,NaN,65af85ae-82d5-5b81-bc66-6bddaa6420ce,True,True,False,2026-04-13 14:50:20.343
505,https://cavatica.sbgenomics.com/public/apps/q?...,2026-04-13 14:54:46.728,True,NaN,65af85ae-82d5-5b81-bc66-6bddaa6420ce,True,True,False,2026-04-13 14:54:46.728
498,https://cavatica.sbgenomics.com/u/sevenbridges...,2026-04-13 14:55:03.675,True,NaN,65af85ae-82d5-5b81-bc66-6bddaa6420ce,True,True,False,2026-04-13 14:55:03.675
375,https://portal.kidsfirstdrc.org/analytics,2026-04-13 14:55:23.219,True,NaN,65af85ae-82d5-5b81-bc66-6bddaa6420ce,True,True,False,2026-04-13 14:55:23.219
310,https://github.com/kids-first/c2m2-submission-...,2026-04-13 14:57:55.095,True,NaN,65af85ae-82d5-5b81-bc66-6bddaa6420ce,True,True,False,2026-04-13 14:57:55.095

In [3]:
current_dcc_assets = dcc_assets[dcc_assets.created.apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S.%f")) > datetime.datetime(2025, 12, 15, 23, 59, 59)]

In [4]:
dcc = pd.read_csv("https://cfde-drc.s3.amazonaws.com/database/files/current_dccs.tsv", sep="\t", index_col=0)

In [5]:
current_dcc_assets["DCC"] = [dcc.loc[i, 'short_label'] for i in current_dcc_assets.dcc_id]

/var/folders/wq/7bkxhy8j7ql194c1fbby4gy40000gn/T/ipykernel_18054/1305888965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_dcc_assets["DCC"] = [dcc.loc[i, 'short_label'] for i in current_dcc_assets.dcc_id]

In [6]:
file_assets = pd.read_csv("https://cfde-drc.s3.amazonaws.com/database/files/current_file_assets.tsv", sep="\t")
file_assets = file_assets.set_index("link")
file_assets.head()

,filetype,filename,size,sha256checksum
link,,,,
https://cfde-drc.s3.amazonaws.com/GTEx/C2M2/2022-01-18/GTEx_C2M2_2022-01-18_datapackage.zip,C2M2,datapackage.zip,384717,NaN
https://cfde-drc.s3.amazonaws.com/GTEx/C2M2/2022-04-07/GTEx_C2M2_2022-04-07_datapackage.zip,C2M2,datapackage.zip,729801,NaN
https://cfde-drc.s3.amazonaws.com/GTEx/C2M2/2022-06-17/GTEx_C2M2_2022-06-17_datapackage.zip,C2M2,datapackage.zip,753127,NaN
https://cfde-drc.s3.amazonaws.com/GTEx/C2M2/2023-09-01/GTEx_C2M2_2023-09-01_datapackage.zip,C2M2,datapackage.zip,9288164172,NaN
https://cfde-drc.s3.amazonaws.com/GlyGen/C2M2/2022-04-15/GlyGen_C2M2_2022-04-15_datapackage.zip,C2M2,datapackage.zip,4059608,NaN

In [7]:
code_assets = pd.read_csv("https://cfde-drc.s3.amazonaws.com/database/files/current_code_assets.tsv", sep="\t")
code_assets = code_assets.set_index("link")
code_assets.head()

,type,name,description,openAPISpec,smartAPISpec,smartAPIURL,entityPageExample
link,,,,,,,
https://brl-bcm.stoplight.io/docs/exrna-atlas-json-api/ZG9jOjQ1Mg-overview,API,exRNA Atlas JSON-LD,NaN,True,False,NaN,NaN
https://github.com/nih-cfde/LINCS-metadata/blob/main/scripts/build_file_lincs2021.py,ETL,build_file_lincs2021.py,NaN,NaN,NaN,NaN,NaN
https://smart-api.info/ui/fdb3ecfcf5006a142d3f5522930324f1,API,SigCom LINCS Data,NaN,True,True,NaN,NaN
https://smart-api.info/ui/75cfc060ea7bec431a356c00c4a67c74,API,SigCom LINCS Metadata,NaN,True,True,NaN,NaN
https://smart-api.info/ui/d2cd419fdeace3e941984bc542e9383f,API,Enrichr,NaN,True,True,NaN,NaN

In [13]:
current_dcc_assets['Asset Type'] = ''
for k,v in current_dcc_assets.iterrows():
	link = v["link"]
	asset = file_assets.loc[link, 'filetype'] if link in file_assets.index else code_assets.loc[link, 'type']
	# asset = file_assets.loc[link, 'filetype'] #if link in file_assets.index else 'ETL'
	current_dcc_assets.loc[k, 'Asset Type'] = asset

/var/folders/wq/7bkxhy8j7ql194c1fbby4gy40000gn/T/ipykernel_18054/4159639814.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_dcc_assets['Asset Type'] = ''

In [14]:
current_dcc_assets[['DCC', 'Asset Type', 'dccapproved', 'drcapproved', 'created', 'deleted', 'current']].sort_values('created', ascending=False).to_csv("032026submissions.tsv", sep="\t", index=False)